- name: install apache 2 and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name : change e-mail address of admin
  tags: apache2,ubuntu,email
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '\tServerAdmin'
    line: 'ServerAdmin somebody@somewhere.net'
  when: ansible_distribution == "Ubuntu"
  register: apache2_var

- name: restart apache2 service (Ubuntu)
  tags: apache2,ubuntu,email
  service:
    name: apache2
    state: restarted
  when: apache2_var.changed

- name: start apache2 (Ubuntu)
  tags: apache2,ubuntu,httpd
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
  register: apache2

- name: install apache and php on CentOS servers 
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
